config/routes.rb
Rails.application.routes.draw do
  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base
    
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.order(:deadline)
    @grouped_months = @accounts.group_by { |r| r.deadline.beginning_of_month}
    @all_total =  Account.sum(:price)
    @months = []
    (1..12).each {|m| @months << m}
    @month_details = []
    @month_costs = []
    (0..11).each do |i|
    @month_details[i] = Account.where(["date_part('month',deadline) = ? and date_part('year',deadline) = ?" , @months[i],2015]).order('deadline desc')
    # @month_costs[i] = Account.where(["date_part('month',deadline) = ? and date_part('year',deadline) = ?" , @months[i],2015]).sum(:price)
    @tab = params[:tab] 
   end
    
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        # format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
        format.html { redirect_to action: :index, tab: @account.deadline.strftime("%m").to_i , notice: 'Account was successfully created.'}
        
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      # params[:account]
      params.require(:account).permit(:deadline, :title, :price ,:title_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<div class="form">
<%= simple_form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :"日期" %></br>
	  <%= f.date_select :deadline , control_col: "col-sm-2" %></br>
   
    <%= f.input :title ,label:"項目" %>
    </br>
    <%= f.input :price ,label:"金額" %>
    
  	
</div>


  <div class="actions">
    <%= f.submit "新增/更新" ,class:'btn btn-success btn-lg'%>
  </div>
<% end %>
</div>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>
<%= link_to 'New Account', new_account_path ,class:'btn btn-success btn-lg'%>

    <div role="tabpanel">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist" id="myTab">
         <% (0..11).each do |i| %>
          <li role="presentation"><a href="#<%= @months[i] %>" role="tab" data-toggle="tab"><%= @months[i] %>月</a></li>
         <% end %>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
         <% (0..11).each do |i| %>
          <div role="tabpanel" class="tab-pane" id="<%= @months[i] %>" >
            <h2><%= @months[i] %>月</h2>
          <table class="table table-hover">
            <tbody>
              <thead>
                <tr>
                  <th>日期</th>
                  <th>項目</th>
                  <th>金額</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
               <% @total=0 %>
               <% @month_details[i].each do |account| %>  
                <tr>
                  <td><%= account.deadline %></td>
            			<td><%= link_to account.title, account_path(account) %></td>
            			<td><%= account.price %></td>
                  <td><%= link_to 'Edit', edit_account_path(account) ,class:'btn btn-warning'%></td>
                  <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger' %></td>
                </tr>
               <% @total+=account.price %>
               <% end %>
                <tr>
                  <th></th>
                  <th>月總計</th>
                  <th colspan="3"><%= @total %></th>
                </tr>
            </tbody>
          </table>
          </div>
        <% end %>
      </div>
    </div>

    <table class="table">
      <tbody>
         <thead>
            <tr>
              <th>總計</th>
              <th><%= @all_total %></th>
              <th></th>
            </tr>
          </thead>
      </tbody>      
    </table>

<script>
// $('#myTab a').click(function (e) {
//   e.preventDefault()
//   $(this).tab('show')
// })
$('#myTab a[href="#<%=params[:tab]%>"]').tab('show') // Select tab by name
</script>
<!--<% @grouped_months.keys.sort.each do |month| %>  -->
<!--<h2><%= month.strftime("%B %Y") %></h2>  -->
<!--<table class='table table-hover'>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>日期</th>-->
<!--      <th>項目</th>-->
<!--      <th>金額</th>-->
<!--      <th colspan="2"></th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
<!--  <% for account in @grouped_months[month] %>  -->
<!--    <tr>-->
<!--      <td><%= account.deadline %></td>-->
<!--			<td><%= link_to account.title, account_path(account) %></td>-->
<!--			<td><%= account.price %></td>-->
<!--      <td><%= link_to 'Edit', edit_account_path(account) ,class:'btn btn-warning'%></td>-->
<!--      <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger' %></td>-->
<!--    </tr>-->
<!--  <% end %> -->
<!--  </tbody>-->
<!--  <tr>-->
<!--    <td colspan="2" style="text-align:right;">總計</td>-->
<!--    <td><%= @all_total %></td>-->
<!--  </tr>-->
<!--</table>-->
<!--<% end %>-->

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>deadline:</strong>
  <%= @account.deadline %>
</p>

<p>
  <strong>title:</strong>
  <%= @account.title %>
</p>

<p>
  <strong>price: </strong>
  <%= @account.price %>
<p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Account0330</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>
</body>
</html>